blog/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from . import views


app_name = 'blog'

urlpatterns = [
    # *** Content ***:
    url(r'^$', views.BlogHome.as_view(), name='home'),
    url(r'^read/(?P<slug>\S+)/$', views.ReadPost.as_view(), name='read_post'),    # TODO: capture `pk` also
    url(r'^write/$', views.WritePost.as_view(), name='write_post'),
    url(r'^delete/(?P<slug>\S+)/$', views.DeletePost.as_view(), name='delete_post'),

    # *** Authentication ***:
    url(r'^login/$', auth_views.login, {'template_name': 'blog/login.html'}, name='login'),
    # url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^logout/$', auth_views.logout_then_login, {'login_url': 'blog:login'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/confirm/$', views.register_confirm, name='register_confirm'),
    url(r'^register/check/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.register_check, name='register_check'),
    url(r'^register/done/$', views.register_done, name='register_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

import time


def user_media_path(instance, filename):
    """
    Returns the path to where a user uploaded file is saved.
    Has the form: user_<id>/YYYY/MMM/filename
    """
    return 'user_{0}/{1}/{2}/{3}'.format(instance.author.id,
                                        time.strftime('%Y'),
                                        time.strftime('%b'),
                                        filename)


@python_2_unicode_compatible
class Article(models.Model):
    # Editable fields:
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to=user_media_path, null=True, blank=True)

    # Non-editable fields:
    slug = models.SlugField(max_length=50, unique=True)
    published_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    word_count = models.PositiveIntegerField()
    # readtimes- slow: 100 wpm, avg: 130 wpm, fast: 160wpm
    read_time_in_mins = models.PositiveIntegerField()

    # # `word_count` and `read_time_in_mins` will be (re)assigned
    # # everytime the article is saved.
    # def save(self, *args, **kwargs):
    #     self.word_count = len(self.content.split())
    #     self.read_time_in_mins = self.word_count / 130  # assuming avg reading speed.
    #     return super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:read_post', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-published_on']

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>{% block head_title %} Blog {% endblock %}</title>
        
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/custom_styles.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                {# Toggle navbar: shows brand and toggle button when collapsed #}
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#nav-header-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'blog:home' %}">Blog</a>
                </div>
                
                {# Content for toggling #}
                <div class="collapse navbar-collapse" id="nav-header-collapse">
                    <ul class="nav navbar-nav">
                        {% block navbar_link %}
                        {% endblock %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'blog:logout' %}">Log out</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        
        
        {# --- Core Javascript files --- #}
        <script src="{% static 'blog/js/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        
        {# --- Page specific scripts --- #}
        {% block javascript %}
        {% endblock %}
    </body>
</html>

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}


{% block content %}
<form action="{% url 'blog:delete_post' slug=object.slug %}" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-default" type="submit" name="confirm" value="Yes">
    <a class="btn btn-default" href="{% url 'blog:read_post' slug=object.slug %}">Cancel</a>
</form>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}


{% block navbar_link %}
    <li>
        <a href="{% url 'blog:write_post' %}">Write post</a>
    </li>
{% endblock %}


{% block content %}
{% if article_list %}
    {% for article in article_list %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h2><a href="{% url 'blog:read_post' slug=article.slug %}">{{ article.title }}</a></h2>
                
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                {% if user == article.author %} You {% else %} {{ article.author.username }} {% endif %} <br>
                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                {{ article.published_on }} <br>
                {{ article.word_count }} words,
                about {{ article.read_time_in_mins }} minute{{ article.read_time_in_mins|pluralize }} of reading<br>
                <hr>
                
                {% if article.image %}
                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <img class="img-responsive img-rounded" src="{{ article.image.url }}">
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <p>{{ article.content|truncatechars:200 }}</p>
                    </div>
                {% else %}
                    <p>{{ article.content|truncatechars:200 }}</p>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    
    {% if is_paginated %}
        <div class="clearfix"></div>
        <nav class="col">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <span aria-hidden="true">&laquo;</span>
                    </li>
                {% endif %}
                <li>
                    <a>{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>
                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <span aria-hidden="true">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% else %}
    <p>No posts yet. Consider <a href="{% url 'blog:write_post' %}">writing one.</a></p>
{% endif %}
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-sm-4 col-sm-offset-4">
    {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    
    {% if next %}
        {% if user.is_authenticated %}
            <p>
                Your account doesn't have access to this page. To proceed,
                please login with an account that has access.
            </p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
    
    <form method="post" action="{% url 'blog:login' %}">
        {% csrf_token %}
        
        {{ form|crispy }}
        
        {% comment %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
        {% endcomment %}
        
        <input class="btn btn-primary" type="submit" value="Login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    
    {# Setup the URLconf and views for password reset #}
    {# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}
    
    <br><br>
    Don't have an account yet? <strong><a href="{% url 'blog:register' %}">Sign Up</a></strong>
    <br><br>
</div>
{% endblock %}

blog/templates/blog/read_post.html
{% extends 'blog/base.html' %}


{% block navbar_link %}
    <li>
        <a href="{% url 'blog:write_post' %}">Write post</a>
    </li>
{% endblock %}


{% block content %}
{% if user == object.author %}
    <a class="btn btn-danger pull-right" href="{% url 'blog:delete_post' slug=object.slug %}">Delete post</a>
{% endif %}
<br>
<h2>{{ object.title }}</h2>

<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
{% if user == article.author %} You {% else %} {{ article.author.username }} {% endif %} <br>
<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
{{ article.published_on }} <br>
{{ article.word_count }} words,
about {{ article.read_time_in_mins }} minute{{ article.read_time_in_mins|pluralize }} of reading<br>
<hr>

{% if object.image %}
    <p><img class="img-responsive img-rounded center-block" style="max" src="{{ object.image.url }}"></p>
{% endif %}
<br>
<p>{{ object.content|linebreaks }}</p>
<br><br>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-sm-4 col-sm-offset-4">
    <p align="center">Sign Up</p>
    
    <form action="{% url 'blog:register' %}" method="post">
    {% csrf_token %}
        <table>
            {{ form|crispy }}
        </table>
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
<br><br>
{% endblock %}

blog/templates/blog/register_confirm.html
{% extends 'blog/base.html' %}

{% block content %}
<br>
<p align="center">Please check your email and click on the verification link to confirm your registration.</p>
<br>
{% endblock %}

blog/templates/blog/register_confirm_email.html
You have registered at the Blog with the following details:
Username: {{ user.username }}
Email: {{ user.email }}

To confirm follow the link below:
{{ protocol }}://{{ domain }}{% url 'blog:register_check' uidb64=uid token=token %}

blog/templates/blog/register_done.html
{% extends 'blog/base.html' %}

{% block content %}
<br>
<p align="center">You have succefully registered.</p>
<strong><p align="center"><a href="{% url 'blog:login' %}">Click here to login</a></p></strong>
<br>
{% endblock %}

blog/templates/blog/write_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block navbar_link %}
<li class="active">
    <a>Write post <span class="sr-only">(current)</span></a>
</li>
{% endblock %}


{% block content %}
{# --- Form --- #}
<form action="{% url 'blog:write_post' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-primary" type="submit" value="Submit">
</form>
<br><br>

{# --- Preview --- #}
<h4>Preview:</h4>
<pre>
    <h2 id="preview-title"></h2><p id="preview-image"></p><p id="preview-content"></p>
</pre>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
    $(document).ready(function() {
        // Preview title
        $("#id_title").on("keyup", function() {
            $("#preview-title").text($(this).val());
        });
        
        // Preview image
        $("#id_image").change(function() {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function(event) {
                    $("#preview-image").html('<img class="img-responsive" src="' + event.target.result + '" alt="selected image">');
                };
                reader.readAsDataURL(this.files[0]);
            }
        });
        
        // Preview content
        $("#id_content").on("keyup", function() {
            $("#preview-content").text($(this).val());
        });
    });
</script>
{% endblock %}